# ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ #
# ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ #
#                                              TicketManager Config File                                              #
#                                                     Version 11.0.3                                                  #
#                                                     Paper Edition                                                   #
# ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ #
# ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ #
#   Information:                                                                                                      #
#       • Plugin Proudly Made By: HoshiKurama.                                                                        #
#       • Plugin details such as permissions and commands are documented on the wiki:                                 #
#         https://github.com/HoshiKurama/TicketManager.                                                               #
#                                                                                                                     #
# ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ #
# ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#                                                Localization Settings                                                #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#   TicketManager supports localization into other languages. Minecraft clients will:                                 #
#       • See translated messages                                                                                     #
#       • Use translated commands                                                                                     #
#       • Receive translated tab-completions.                                                                         #
#                                                                                                                     #
#   Exceptions for localizations are                                                                                  #
#       • Player names                                                                                                #
#       • Ticket comments.                                                                                            #
#                                                                                                                     #
#   Note: In the past, TicketManager supported simultaneous localization, where multiple localizations were loaded    #
#         and used on a per-client basis. This feature has been removed to reduce complexity. Any users adversely     #
#         impacted by this change should join the Discord server and express your desire to see the feature return.   #
#                                                                                                                     #
#                                              Supported Localizations:                                               #
#                                     ╔═══════════╤══════════════════════════════╗                                    #
#                                     ║   Value   │           Language           ║                                    #
#                                     ╠═══════════╪══════════════════════════════╣                                    #
#                                     ║  'de_de'  │ German                       ║                                    #
#                                     ║  'en_ca'  │ Canadian English             ║                                    #
#                                     ║  'en_uk'  │ UK English                   ║                                    #
#                                     ║  'en_us'  │ US English                   ║                                    #
#                                     ╚═══════════╧══════════════════════════════╝                                    #
#                                                                                                                     #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Preferred_Locale: "en_ca"
#   Locale that TicketManager will use.                                                                               #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#                                            Time-Based Cool-down Settings                                            #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#   Time-based cool-downs prevent users from spamming tickets within a short timespan. They are applied to:           #
#       • Ticket creations (create)                                                                                   #
#       • Ticket modifications (comment, setpriority, close, etc).                                                    #
#                                                                                                                     #
#    Cool-downs apply to ALL users without the override permission.                                                   #
#                                                                                                                     #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Use_Cooldowns: false
#   Enable or disable time-based cool-downs.                                                                          #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Cooldown_Time: 0
#   Time in seconds (must be an integer) between allowed ticket interactions.                                         #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#                                                    Proxy Settings                                                   #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#   Proxy mode offers a few benefits:                                                                                 #
#       • Notification broadcasting across all servers                                                                #
#       • Teleporting to tickets on any connected servers.                                                            #
#       • Running Discord notifications on just the proxy                                                             #
#                                                                                                                     #
#   Please note that the target server must and have at least 1 player online to function.                            #
#                                                                                                                     #
#   TicketManager officially supports:                                                                                #
#       • Velocity (Recommended)                                                                                      #
#       • Waterfall                                                                                                   #
#   Compatibility with Bungeecord is not tested, and issues with the proxy will be ignored.                           #
#                                                                                                                     #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Enable_Proxy: false
#   Enable or disable proxy mode.                                                                                     #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Proxy_Server_Name: ''
#   Server name given in your proxy file.                                                                             #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Allow_Proxy_UpdateChecking: true
#   Allow the server to check for new proxy versions.                                                                 #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#                                                 Chat Format Settings                                                #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
Colour_Code: '&3'
#   TicketManager provides a means to change its theme colours and supports multiple formats:                         #
#       • Colour Literals ('red', 'white', etc)                                                                       #
#       • Hex Codes ('#17ad98')                                                                                       #
#       • Integers ('1551768')                                                                                        #
#       • Legacy Colour Codes ('&3', '&c', etc).                                                                      #
#                                                                                                                     #
#   Please refer to Kyori MiniMessage for more information.                                                           #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Enable_Advanced_Visual_Control: false
#   TicketManager provides a means for end-users to safely configure plugin visuals. When enabled, the plugin will    #
#   read from and use the visual localization files inside the TicketManager plugin folder. To understand the         #
#   formatting, please refer to Kyori MiniMessage documentation.                                                      #
#                                                                                                                     #
#   Two notable safely precautions occur when enabled:                                                                #
#       • Missing files re-generate                                                                                   #
#       • Missing components default to the internal version.                                                         #
#                                                                                                                     #
#   Note: If interested in translating TicketManager to your language, please consider contacting HoshiKurama to      #
#   discuss creating an official translation file!                                                                    #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
#                                               Plugin Update Settings                                                #
#   ══════════════════════════════════════════════════════════════════════════════════════════════════════════════    #
Allow_Unread_Ticket_Updates: true
#   Alert ticket creators at regular intervals or on login that they have a status change on a ticket. This is NOT    #
#   the same alert that users receive immediately for the same thing. Setting this value to 'false' prevents the      #
#   plugin from flagging a ticket as unread.                                                                          #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Allow_UpdateChecking: true
#   Allow the server to check for newer version of TicketManager.                                                     #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #
Auto_Update_Config: true
#   Allow this config file to automatically update and transfer existing config settings.                             #
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────    #